apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: gethomepage/homepage:latest
        resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: homepage-config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: homepage-config-volume
    configMap:
      name: homepage-config
      items:
        - key: kubernetes.yaml
          path: kubernetes.yaml
        - key: settings.yaml
          path: settings.yaml
        - key: custom.css
          path: custom.css
        - key: custom.js
          path: custom.js
        - key: bookmarks.yaml
          path: bookmarks.yaml
        - key: services.yaml
          path: services.yaml
        - key: widgets.yaml
          path: widgets.yaml
        - key: proxmox.yaml
          path: proxmox.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
spec:
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31300
  type: NodePort