apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: default
data:
  qbittorrent.conf: |
    [BitTorrent]
    Session\AddTorrentStopped=false
    Session\Port=6881
    Session\QueueingSystemEnabled=true
    Session\SSL\Port=41125
    Session\ShareLimitAction=Stop

    [Meta]
    MigrationVersion=8

    [Network]
    Proxy\HostnameLookupEnabled=false
    Proxy\Profiles\BitTorrent=true
    Proxy\Profiles\Misc=true
    Proxy\Profiles\RSS=true

    [Preferences]
    WebUI\BypassAuthentication=true
    WebUI\CSRFProtection=false
    WebUI\HostHeaderValidation=false
    WebUI\TrustedInterfaces=0.0.0.0/0
    WebUI\Port=8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.0
    - hard
  nfs:
    server: 192.168.100.91
    path: /volumeUSB2/usbshare
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: qbittorrent-downloads-pv
